In [33]:
import pandas as pd
import numpy as np
import time
import os
os.getcwd()

'/Users/hongling/Desktop/HW4'

In [34]:
file = "/Users/hongling/Desktop/HW4/pensioners.csv"
data = pd.read_csv(file)

In [36]:
class aggregator(object):

    def __init__(self):
        self.xsum=0.0;
        self.n=0.0
        
    def add(self, x):
        self.xsum+=x
        self.n+=1
        
    def count(self):
        return self.n
    
    def sum(self):
        return self.xsum
    
    def mean(self):
        self.mean=self.xsum/self.n
        return self.mean

In [37]:
# 新建一个空表来装annual indicators
indicators=pd.DataFrame(index=list(range(2015,2041)),columns=["Total pension","Total pension of all males","Total pension of all females","Average age of all pensioners","Number of all pensioners","Average pension amount","Average pension amount (male)","Average pension amount (female)"])

In [38]:
data.loc["813691"]=0 #加上一行，不然下面的代码总是报错“single positional indexer is out-of-bounds”。。。。
data.iloc[[-1],[0]]=2041

In [43]:
t0=time.time()

pension=aggregator()
age=aggregator()
male_pension=aggregator()
female_pension=aggregator()
year=2015
i=0

while data.shape[0]-i: #从第一行到最后一行
    if data.iloc[i][0]==year : #对当前年份
        pension.add(data.iloc[i][2]) #把这一年所有lastpension加起来
        age.add(data.iloc[i][3]) #把这一年所有age加起来
        if data.iloc[i][5]==1: #如果为男性
            male_pension.add(data.iloc[i][2]) #就加到male_pension里面去
        else: #如果为女性
            female_pension.add(data.iloc[i][2]) #就加到female_pension里面去
        i+=1 #转到下一行
    else: #如果year到了下一年
        indicators.loc[year]["Total pension"]=pension.sum()
        indicators.loc[year]["Total pension of all males"]=male_pension.sum()
        indicators.loc[year]["Total pension of all females"]=female_pension.sum()
        indicators.loc[year]["Average age of all pensioners"]=age.mean()
        indicators.loc[year]["Number of all pensioners"]=pension.count()
        indicators.loc[year]["Average pension amount"]=pension.mean()
        indicators.loc[year]["Average pension amount (male)"]=male_pension.mean()
        indicators.loc[year]["Average pension amount (female)"]=female_pension.mean()
        year+=1
        pension=aggregator()
        age=aggregator()
        male_pension=aggregator()
        female_pension=aggregator()
        
print(time.time()-t0) #execution time

494.8493318557739

In [44]:
indicators

,Total pension,Total pension of all males,Total pension of all females,Average age of all pensioners,Number of all pensioners,Average pension amount,Average pension amount (male),Average pension amount (female)
2015,2.64473e+08,6.83453e+07,1.96127e+08,67.8439,30392,8702.04,10058.2,8311.53
2016,2.33792e+08,6.90781e+07,1.64714e+08,63.0501,22161,10549.7,10255.1,10678.4
2017,2.4017e+08,7.24595e+07,1.67711e+08,62.575,22608,10623.2,10120,10856.5
2018,2.47289e+08,7.61813e+07,1.71107e+08,62.2448,23043,10731.6,10029.1,11077.1
2019,2.54525e+08,8.0565e+07,1.7396e+08,62.1195,23391,10881.3,10095.9,11288
2020,2.64671e+08,8.61041e+07,1.78567e+08,62.0329,23893,11077.4,10205.5,11553.3
2021,2.76172e+08,9.22048e+07,1.83967e+08,62.0111,24439,11300.4,10368.2,11833.7
2022,2.9021e+08,9.86364e+07,1.91573e+08,62.1011,25084,11569.5,10575.4,12158
2023,3.08277e+08,1.073e+08,2.00977e+08,62.2807,25896,11904.4,10857.1,12550.9
2024,3.2742e+08,1.16687e+08,2.10734e+08,62.5392,26669,12277.2,11201.6,12966.6
2025,3.50027e+08,1.28214e+08,2.21814e+08,62.8364,27543,12708.4,11636.8,13422.9
2026,3.73761e+08,1.39846e+08,2.33915e+08,63.1608,28322,13196.9,12097.4,13955.1
2027,3.98788e+08,1.52779e+08,2.46009e+08,63.516,29098,13705,12584.8,14507
2028,4.29302e+08,1.68057e+08,2.61245e+08,63.8689,30044,14289.1,13133.6,15146.4
2029,4.61337e+08,1.83911e+08,2.77426e+08,64.2297,31003,14880.4,13697.1,15784.4
2030,4.97326e+08,2.01929e+08,2.95398e+08,64.6201,32112,15487.2,14242.4,16471.4
2031,5.35288e+08,2.20882e+08,3.14406e+08,64.9951,33181,16132.4,14817.3,17205.1
2032,5.76412e+08,2.43008e+08,3.33405e+08,65.3816,34354,16778.6,15413.4,17936.6
2033,6.19272e+08,2.65753e+08,3.53519e+08,65.7348,35557,17416.3,15979.4,18679
2034,6.61403e+08,2.89384e+08,3.72019e+08,66.0904,36719,18012.6,16563.7,19327.7
2035,7.07511e+08,3.15393e+08,3.92118e+08,66.4383,37977,18630,17177.3,19989.7
2036,7.54452e+08,3.41519e+08,4.12934e+08,66.8087,39259,19217.3,17732,20647.7
2037,8.0623e+08,3.70277e+08,4.35953e+08,67.161,40654,19831.5,18315.1,21331.6
2038,8.55358e+08,3.98449e+08,4.56909e+08,67.5304,41936,20396.7,18876.7,21937.3
2039,9.10429e+08,4.27142e+08,4.83286e+08,67.8681,43427,20964.6,19368.9,22610.9
2040,9.65624e+08,4.58046e+08,5.07578e+08,68.2158,44929,21492.2,19856.4,23218.4